# Generated by Django 4.1.5 on 2023-01-23 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='current_direction',
            field=models.CharField(choices=[('up', 'Up'), ('down', 'Down'), ('idle', 'Idle')], default='idle', max_length=10),
        ),
        migrations.CreateModel(
            name='ElevatorRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('request_time', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_system.elevator')),
            ],
        ),
    ]
