# Generated by Django 4.1.5 on 2023-01-23 14:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0002_elevator_current_direction_elevatorrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevator',
            name='capacity',
            field=models.IntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='floor',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='last_maintenance',
            field=models.DateField(default='2022-11-01'),
        ),
        migrations.AlterField(
            model_name='elevator',
            name='status',
            field=models.CharField(default='Active', max_length=30),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor', models.IntegerField()),
                ('direction', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elevator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_system.elevator')),
            ],
        ),
    ]
