# Generated by Django 4.1.5 on 2023-01-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0003_alter_elevator_capacity_alter_elevator_floor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevator',
            name='elevator_id',
            field=models.IntegerField(default=0),
        ),
    ]
