# Generated by Django 4.1.5 on 2023-01-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0004_elevator_elevator_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='elevator',
            name='elevator_id',
        ),
        migrations.AddField(
            model_name='elevator',
            name='door_status',
            field=models.CharField(default='Close', max_length=30),
        ),
    ]
